List<Map<String, String>> imageConst = [
  {"image": 'assets/images/Alphintern.jpg', "name": 'Alphintern'},
  {"image": 'assets/images/Ambezim.jpg', "name": 'Ambezim'},
  {"image": 'assets/images/Amophage.jpg', "name": 'Amophage'},
  {"image": 'assets/images/Antinal.jpg', "name": 'Antinal'},
  {"image": "assets/images/Augmentin.jpg", "name": "Augmentin"},
  {"image": "assets/images/Betacor.jpg", "name": "Betacor"},
  {"image": "assets/images/Clavimox.jpg", "name": "Clavimox"},
  {"image": "assets/images/Concor.jpg", "name": "Concor"},
  {"image": "assets/images/Corasore.jpg", "name": "Corasore"},
  {"image": "assets/images/Decancit.jpg", "name": "Decancit"},
  {"image": "assets/images/Fleboton.jpg", "name": "Fleboton"},
  {"image": "assets/images/Gast-Reg.jpg", "name": "Gast-Reg"},
  {"image": "assets/images/Glucovance.jpg", "name": "Glucovance"},
  {"image": "assets/images/Haemoton.jpg", "name": "Haemoton"},
  {"image": "assets/images/Kapron.jpg", "name": "Kapron"},
  {"image": "assets/images/Librax.jpg", "name": "Librax"},
  {"image": "assets/images/Lustral.jpg", "name": "Lustral"},
  {"image": "assets/images/Mebo cream.jpg", "name": "Mebo cream"},
  {"image": "assets/images/Mixtard.jpg", "name": "Mixtard"},
  {"image": "assets/images/Ofev.jpg", "name": "Ofev"},
  {"image": "assets/images/Oracure.jpg", "name": "Oracure"},
  {"image": "assets/images/Otrivin.jpg", "name": "Otrivin"},
  {"image": "assets/images/Roaccutan.jpg", "name": "Roaccutan"},
  {"image": "assets/images/Tiratam.jpg", "name": "Tiratam"},
  {"image": "assets/images/Utoral.jpg", "name": "Utoral"}
];
